### ISSUE TITLE
(Request) Linux Binary 

### ISSUE THREAD

**Issue by alphafox02** [softsyst/RSP3_tcp#2]
I hadn’t got around to an attempt at building this for Linux, but thought I’d check back to see if that was still something you were considering. 

I’ve tried the normal rsp_tcp now with Linux and it seems limited in what it can do without using the extio - like I just want to adjust gain and that doesn’t seem to be an option.

**Comment by softsyst** [comment]
The RSP3_tcp is still in the pipeline, just had to wait due to other activities. I hope to try it soon.
Thanks for the remark!

**Comment by alphafox02** [comment]
No problem! I’ve found it somewhat confusing if not impossible to adjust some of the gain settings (without extio) using the normal rsp_tcp for version 3.x api

**Comment by alphafox02** [comment]
Hi again. Someone reminded me of rsp_tcp and that got me thinking about this project again. Any chance a Linux build is still in the pipeline? Thanks

**Comment by alphafox02** [comment]
I see the main branch moved on to 3.10 api, perhaps the Linux version would still need to be 3.7.

**Comment by softsyst** [comment]
Linux build V0.9.6 released, sources identical to Windows.

**Comment by alphafox02** [comment]
Yes! Can’t wait to try. Curious if bias and other settings are supported.

**Comment by alphafox02** [comment]
Giving it a quick try and seeing this, assuming maybe I can just ignore and it's something to do with newer api on windows?

```
Starting sdrplay...
sdrplay_api_Open successful
sdrplay API dll Version 3.07
*** Warning : API version don't match (local=3.10 dll=3.07)
```

So far I'm not seeing anything come across in the applications I'd normally use rtl_tcp. GQRX, SDR++, and SDRAngel. However with the standard rsp_tcp I can get a connection and stream. 

This is what I see on RSP3_TCP
```
**** receive thread entered.   *****
**** I/Q data transmit thread entered.   *****
```
Then if i stop the application that's trying to stream from it, I'll end up getting this. 

```
Uninitializing... 0
Segmentation fault (core dumped)
```
I should maybe open a separate ticket for this.

**Comment by softsyst** [comment]
Hi alphafox02,

RSP3_tcp in its latest version is intended to cooperate with the QIRX software, in particular its version 4 (see README). As I do not know the other apps you are mentioning, I cannot comment on them.
Some remarks though:

- Linux still uses the sdrplay API 3.07, on Windows the API 3.10 is used. This is mentioned also in the README. Here, this was no problem. 
- When using the software with QIRX, it prompts you to select one of possibly more than one RSP devices from a list, very similar to SDRUno. For this to work, RSP3_tcp cooperates with QIRX in a handshake-like exchange of telegrams, which most probably is not realized in one of the other apps you are mentioning. For this, and also for information reported back from the device, like total gain, LNA state etc, a second TCP/IP channel is used, listening on a port number one larger than the one from I/Q data channel. Here 7890 and 7891. These you see down in the screenshots.
- This protocol also runs silently even if you have only one RSP device connected. As a consequence, the client (QIRX) must implement it.

What you should see after having started RSP3_tcp in Linux is the following (here Debian 11, QIRX 4.07 on Win10):
After starting RSP3_tcp:
![Screenshot from 2023-03-21 11-47-04](https://user-images.githubusercontent.com/51386375/226589633-fadb580f-73d7-4571-9ea8-41a2a046aabb.png)

After having connected twice. For the first start, I need to do it twice, reason still unknown:
![Screenshot from 2023-03-21 11-50-23](https://user-images.githubusercontent.com/51386375/226589957-c73fe27a-bab1-4c32-930c-9bcd20078ad5.png)

And, running and terminating with Ctrl-C:
![Screenshot from 2023-03-21 11-53-47](https://user-images.githubusercontent.com/51386375/226590715-4844e4c7-125a-4dfa-9c77-39f4807311eb.png)

I/Q data are coming after the successful `sdr_api_StreamInit `command, 2nd screenshot.
Here, I could not observe crashes.

Regards,
Clem

**Comment by alphafox02** [comment]
It makes sense now what’s going on. I mistakenly thought I could use it with other rtl_tcp/rsp_tcp compatible applications. I’ll give it a try with QIRX.

**Comment by softsyst** [comment]
Maybe you noticed that the latest version got the commandline parameter -B [0|1], means Basic. -B 0 is the default for QIRX, -B 1 is the "basic" version compatible with rtl_tcp. Should work on Linux too. Tested with DAB player (parameter -rtltcp), and SDR#, rtl-tcp selected as device.

**Comment by alphafox02** [comment]
Sorry I missed that last explanation, I’ll give it a try!
