### ISSUE TITLE
Not an issue, just a typo

### ISSUE THREAD

**Issue by edd-cgfan** [softsyst/RSP3_tcp#3]
Hi Clem,

please have look at lines 935 and 936 in file sdrplay_device.cpp:
The command line output 
"sdrplay_api_AgcControl 50Hz, -60 dBfs returned with: 0"
should be
"sdrplay_api_AgcControl 5Hz, -15 dBfs returned with: 0"
because of 
pCurCh->ctrlParams.agc.enable = sdrplay_api_AGC_5HZ;
and 
agcPoint_dBfs should be replaced with agcPoint_dBfs_DAB in line 936 because of line 934.

Best regards,
cgfan

Edit: agcPoint_dBfs replacement added.

**Comment by softsyst** [comment]
Ok, corrected, thanks.
