### ISSUE TITLE
Add support for rsp1b

### ISSUE THREAD

**Issue by tixsys** [softsyst/RSP3_tcp#4]
Add support for rsp1b please

**Comment by softsyst** [comment]
Thx for hint. Just had a look at the API. Apart from the new id, the only change seems to be the new frequency range 50-60MHz for the gain settings, Are you aware of any other difference? The newly installed sdrplay service reports V3.14 and is running with the current RSP3_tcp software.

**Comment by softsyst** [comment]
Version 0.3.11 extended the hardware ranges to the RSP1B and the RSPdxR2.
SDRplay API Version is now 3.15
